### ISSUE TITLE
Inform the tab that the connection was closed

### ISSUE THREAD

**Issue by fregante** [Cacodaimon/GhostText-for-Chrome#13]
Following Cacodaimon/GhostTextForSublimeText#14 we need to properly close the connection in the tab since the textarea highlight and event listeners currently stay on.

**Comment by JokerQyou** [comment]
Sorry to comment on a closed issue, but is this related to the message which appears after the Sublime Text tab closed? I did see an error message each time I finish editing in the Sublime Text tab. I think maybe there is a way to avoid this? 
Maybe we could send a signal to the Chrome extension, saying 'Tab closed, editing finished' and pop up a more user-friendly message other than 'Connection closed' or so. 
And thanks for this useful extension, it really make life easier. :)

**Comment by Cacodaimon** [comment]
@JokerQyou 

Feel free to open a new issue about it, otherwise it is possible that it got forgotten quickly, in this closed issue ;) .
