### ISSUE TITLE
Once GT is connected on a page, "follow field focus", use whatever focused field

### ISSUE THREAD

**Issue by bfred-it** [Cacodaimon/GhostText-for-Chrome#34]
We don't support multiple fields on a page, but apparently there are use cases for them. #33 is one, CodePen.io is the other very-nice-to-have is the other one (CodeMirror)

Instead of opening a connection and editor tab for each field, we could just automatically follow the user focus:

1. User focuses on a field
2. Clicks on GT icon to open connection
3. User focuses a different field
4. GT deactivates the previous field and automatically activates on the new field

![follow focus](https://cloud.githubusercontent.com/assets/1402241/3603088/9fbb090e-0d13-11e4-8af1-1fa19cec00d6.gif)
(this gif highlights on hover, but I mean on focus)

Instead of connecting `1 Field <-> 1 ST tab`, we can just keep it `1 Ch tab <-> 1 ST tab`

**Comment by jschuur** [comment]
For CodePen, it would make more sense to not have to switch focus all the time when you're moving between your HTML, CSS and JavaScript tabs. I'd rather just set them up once by opening multiple textearea boxes in Sublime Text.

**Comment by Cacodaimon** [comment]
This is a good point, maybe we should just allow multiple editable elements which belongs to one tab beeing connected with ST at the same time?

**Comment by jschuur** [comment]
Why one tab? I'd still want to keep JS, CSS and HTML in distinct tabs on Sublime Text.

**Comment by Cacodaimon** [comment]
I was talking about browser tabs the chrome/firefox extension currently "talks" to one editable per tab.

**Comment by bfred-it** [comment]
What @jschuur is saying makes sense, being able simply switch ST tab would be ideal (instead of going back and forth to the browser and switching field with the mouse)

If we support this, we'll have to find a way to enable this behavior too. Currently the GT button is a simple on/off, so how do we _enable_ a secondary field?

* Do we connect any area that the user clicks on while GT is enabled? 
* Do we turn it into a "connect another field" button and then provide a secondary "Stop connection" button somewhere on the page?

**Comment by Cacodaimon** [comment]
@bfred-it 
You are right integrating this into the UI in a simple way is not easy…
I personally like your first solution "Do we connect any area that the user clicks on while GT is enabled?"
In this case we could show the number of connected editables instead of the on/off indicator in the button.
Is a stop button per editable really needed or can one global stop button closing all connections can do the job?

**Comment by bfred-it** [comment]
Right, should the user want to close one connection they can just close the ST tab. 

I'm on board with the connection count in the button.

We can add a stop sign in the button as well when it's enabled.

**Comment by fregante** [comment]
Moved back to https://github.com/GhostText/GhostText/issues/49
