### ISSUE TITLE
Support fields within frames (Disqus)

### ISSUE THREAD

**Issue by bfred-it** [Cacodaimon/GhostText-for-Chrome#36]
Test page here: https://help.disqus.com/customer/portal/questions/6515747-how-can-i-delete-discussions-

GT can't see the textarea in that iframe, it's a different document. Problem is… there is a _wontFix bug_ on Chromium: https://code.google.com/p/chromium/issues/detail?id=57601

I'll have to look further into this, we might have to go back to the always-loaded content.js (which might have the same issue, but I don't know)

**Comment by fregante** [comment]
Moved to https://github.com/GhostText/GhostText/issues/75
