### ISSUE TITLE
GhostText doesn't fire all key events

### ISSUE THREAD

**Issue by Cacodaimon** [Cacodaimon/GhostText-for-Chrome#43]
Origin Issue: https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/42#issuecomment-64977901

**Comment by Cacodaimon** [comment]
@Azeirah

Can you provide a example page which uses key events which I can use for testing?

**Comment by Azeirah** [comment]
[brainstorm-notes.meteor.com](here you go)

**Comment by Cacodaimon** [comment]
I have implemented the keyup event first, it seems that the preview function from the provided page works fine.

@bfred-it 
Can you upload a new version to the Chrome web store or shall we implement the other two event first?

**Comment by fregante** [comment]
Moved back to https://github.com/GhostText/GhostText/issues/42 on the main repo
