### ISSUE TITLE
GhostText can't handle multiple file tabs in Codecademy

### ISSUE THREAD

**Issue by seanf** [Cacodaimon/GhostText-for-Chrome#45]
Codecademy's [HTML & CSS track](http://www.codecademy.com/courses/web-beginner-en-UuBLw/0/1) lets the user switch between separate files for HTML and CSS.  I'm not sure whether the same textarea is used, but the file contents are replaced when switching tabs, and the same part of the screen stays highlighted as if it were connected to GhostText.  However, the new file contents are not shown in Sublime Text.

Once GhostText is connected, it binds to the active file, and won't edit the other file unless the page is entirely reloaded.  For instance, disconnecting, switching files and reconnecting just connects to the original file.  

This also means GhostText can keep updating a file which is no longer visible (eg it keeps editing HTML after the user switches the view to CSS).  (When this happens, Codecademy doesn't notice the changes, unless the user switches to the file again and makes another change in Sublime Text.)

**Comment by Cacodaimon** [comment]
Thanks for the bug report.

It seems they reuse the same [Ace](http://ace.c9.io/#nav=about) editor instance for all tabs, I can't promise you that this is fixable, but we will give our best.

**Comment by fregante** [comment]
Moved to https://github.com/GhostText/GhostText/issues/84
