### ISSUE TITLE
No longer working in Chrome

### ISSUE THREAD

**Issue by jimpoulakos** [Cacodaimon/GhostText-for-Chrome#46]
Since Chrome updated last week to 

- Version 43.0.2357.124 m

GhostText is no longer able to connect to Sublime Text
![ghosttext](https://cloud.githubusercontent.com/assets/5738078/8281883/c6a24820-18b1-11e5-9bdb-c22288573c9e.PNG)

**Comment by bfred-it** [comment]
It works fine on `44.0.2403.52 beta`, but I do see that error occasionally. Try restarting both apps or rebooting your computer. 

Are you on Windows? Do you see any errors in Chrome's or Sublime's console?

**Comment by jimpoulakos** [comment]
Sorry for the late response. I've been using the Firefox version since this stopped working in Chrome.

I went to check and get the error for you from Chrome and Sublime text, but apparently the issue has resolved itself (probably due to an update to Chrome).

This issue can be marked as resolved, as I have no way of getting more information at this time.
