### ISSUE TITLE
Ghost is opening 2 to 7 tabs when clicking in

### ISSUE THREAD

**Issue by Ankiewicz** [Cacodaimon/GhostText-for-Chrome#47]

**Comment by Cacodaimon** [comment]
Please provide the browser version, OS + version , ST version and the post important, the webpage which causes this error.

**Comment by Ankiewicz** [comment]
Browser, Chrome, OS X yosemite, v10.10.4... The webpage causing the error every single one. Sublime text 3

**Comment by Cacodaimon** [comment]
What says the ST error log (you can find it in the ST console)?

**Comment by Ankiewicz** [comment]
It isn’t reading an error that I have seen. I just opens repeats the open 5 times.

**Comment by fregante** [comment]
Moved to https://github.com/GhostText/GhostText/issues/57
