### ISSUE TITLE
blank render

### ISSUE THREAD

**Issue by Ankiewicz** [Cacodaimon/GhostText-for-Chrome#50]
When I click into my editable area, my sublime text renders blank. It is only occuring in Marketo, Marketing software.

**Comment by Cacodaimon** [comment]
Can you provide me an access to the software you are using for debugging purposes?

**Comment by Ankiewicz** [comment]
unfortunately I can not. I apologize. I just wanted to make you all aware
of the issue. I love GHOST TEXT

**Comment by bfred-it** [comment]
It's difficult to debug inaccessible environments
