### ISSUE TITLE
Multi-caret editing. Sublime text 3 + Chrome

### ISSUE THREAD

**Issue by kolosovski** [Cacodaimon/GhostText-for-Chrome#54]
Hi,
Thank you for such a superb ad-don, first of all.
Could you please shed some light on multi-caret editing capabilities, when I'm trying to do that the multi-cursor disappears after first char entered, leaving only one cursor. Is it by design? :(

**Comment by fregante** [comment]
This repo is closed (https://github.com/Cacodaimon/GhostText-for-Chrome/issues/52)

The multicaret should work in SublimeText: ![](https://github.com/GhostText/GhostText/raw/master/promo/demo.gif)

(note the multicaret in the for loop)
